#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE ROLE "$TUVERMIND_DB_USER"
 WITH
  NOCREATEDB
  NOCREATEROLE
  LOGIN
  PASSWORD '$TUVERMIND_DB_PASSWORD';
CREATE DATABASE tuvermind OWNER "$TUVERMIND_DB_USER";
EOSQL