# Generated by Django 2.2.15 on 2020-09-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatableTODOHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_at', models.DateTimeField(null=True)),
                ('completion_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=2048)),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatableTODO',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todoes.TODO')),
                ('repeat_every_minutes', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ManyToManyField(to='todoes.RepeatableTODOHistory')),
            ],
            bases=('todoes.todo',),
        ),
    ]
