# Generated by Django 2.2.15 on 2020-09-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedTODOSchedule',
            fields=[
                ('clockedschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.ClockedSchedule')),
                ('_todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.clockedschedule',),
        ),
        migrations.CreateModel(
            name='CrontabTODOSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.CrontabSchedule')),
                ('_todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='IntervalTODOSchedule',
            fields=[
                ('intervalschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.IntervalSchedule')),
                ('_todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=2048)),
                ('done', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TODOHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_at', models.DateTimeField(null=True)),
                ('completion_confirmation', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoes.TodoTask')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatableTODO',
            fields=[
                ('todotask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todoes.TodoTask')),
                ('clocked_schedule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.ClockedTODOSchedule')),
                ('crontab_schedule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.CrontabTODOSchedule')),
                ('interval_schedule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.IntervalTODOSchedule')),
            ],
            bases=('todoes.todotask',),
        ),
    ]
