# Generated by Django 2.2.15 on 2020-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'repeat every selected count of minutes'), (1, 'repeat in selected day of every month'), (2, 'repeat every year in selected day'), (4, 'repeat every selected day of week')])),
                ('value', models.CharField(default=None, max_length=8, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTaskReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_for_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(null=True)),
                ('planned_completion_date', models.DateField(default=None, null=True)),
                ('planned_completion_time', models.TimeField(default=None, null=True)),
                ('reminders', models.ManyToManyField(to='todoes.TodoTaskReminder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledTodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(null=True)),
                ('reminders', models.ManyToManyField(to='todoes.TodoTaskReminder')),
                ('repeats', models.ManyToManyField(to='todoes.RepeatVariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
