# Generated by Django 2.2.15 on 2021-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('inProcess', 'inProcess'), ('completed', 'completed'), ('archived', 'archived'), ('expired', 'expired')], default='pending', max_length=16),
        ),
        migrations.DeleteModel(
            name='TodoStatus',
        ),
    ]
