# Generated by Django 2.2.15 on 2020-09-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepeatableTODO',
            new_name='ScheduledTodoTask',
        ),
    ]
