# Generated by Django 2.2.15 on 2020-09-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='repeatable',
        ),
    ]
