# Generated by Django 2.2.15 on 2020-10-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0002_auto_20201031_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtodotask',
            name='description',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtodotask',
            name='title',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
