# Generated by Django 2.2.23 on 2021-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0002_auto_20210429_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='end_date',
        ),
        migrations.AddField(
            model_name='todotask',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('inProcess', 'inProcess'), ('completed', 'completed'), ('archived', 'archived'), ('expired', 'expired'), ('suspense', 'suspense')], default='pending', max_length=16),
        ),
    ]
