# Generated by Django 2.2.15 on 2020-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0003_auto_20200908_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
