# Generated by Django 2.2.23 on 2021-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0003_auto_20210528_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
