# Generated by Django 2.2.15 on 2020-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0003_auto_20200921_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotaskhistory',
            name='completion_confirmation',
        ),
        migrations.AddField(
            model_name='todotaskhistory',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
