# Generated by Django 2.2.15 on 2020-09-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0004_auto_20200921_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTaskReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_at', models.DateTimeField(null=True)),
                ('completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='todotask',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='TodoTaskHistory',
        ),
        migrations.AddField(
            model_name='todotaskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', related_query_name='reminder', to='todoes.TodoTask'),
        ),
    ]
