# Generated by Django 2.2.15 on 2020-09-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0004_todo_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatabletodo',
            name='repeat_every_minutes',
        ),
        migrations.RemoveField(
            model_name='repeatabletodo',
            name='start_at',
        ),
    ]
