# Generated by Django 2.2.15 on 2020-09-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('todoes', '0005_auto_20200911_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedTODOSchedule',
            fields=[
                ('clockedschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.ClockedSchedule')),
                ('todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.clockedschedule',),
        ),
        migrations.CreateModel(
            name='CrontabTODOSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.CrontabSchedule')),
                ('todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='IntervalTODOSchedule',
            fields=[
                ('intervalschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.IntervalSchedule')),
                ('todo', models.BooleanField(default=True)),
            ],
            bases=('django_celery_beat.intervalschedule',),
        ),
    ]
