# Generated by Django 2.2.15 on 2020-09-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0005_auto_20200927_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotaskreminder',
            old_name='completed',
            new_name='when',
        ),
        migrations.RemoveField(
            model_name='todotaskreminder',
            name='notify_at',
        ),
    ]
