# Generated by Django 2.2.15 on 2020-09-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoes', '0006_clockedtodoschedule_crontabtodoschedule_intervaltodoschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockedtodoschedule',
            old_name='todo',
            new_name='_todo',
        ),
        migrations.RenameField(
            model_name='crontabtodoschedule',
            old_name='todo',
            new_name='_todo',
        ),
        migrations.RenameField(
            model_name='intervaltodoschedule',
            old_name='todo',
            new_name='_todo',
        ),
        migrations.AddField(
            model_name='repeatabletodo',
            name='crontab_schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.CrontabTODOSchedule'),
        ),
        migrations.AddField(
            model_name='repeatabletodo',
            name='interval_schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.IntervalTODOSchedule'),
        ),
        migrations.AddField(
            model_name='todo',
            name='until',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoes.ClockedTODOSchedule'),
        ),
    ]
