__all__ = [
    "CELERY_ACCEPT_CONTENT", "CELERY_BEAT_SCHEDULE", "CELERY_BROKER_URL", "CELERY_ENABLE_UTC", "CELERY_IMPORTS",
    "CELERY_RESULT_BACKEND", "CELERY_RESULT_SERIALIZER", "CELERY_TASK_RESULT_EXPIRES", "CELERY_TASK_SIRIALIZER",
    "CELERY_TIMEZONE"
]

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_TASK_RESULT_EXPIRES = 600
CELERY_ACCEPT_CONTENT = ['application/json', 'application/x-python-serialize']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SIRIALIZER = 'json'
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Etc/UTC'
CELERY_BEAT_SCHEDULE = {}
CELERY_IMPORTS = ('tasks',)
