# Generated by Django 2.2.5 on 2019-09-30 16:25

from django.db import migrations, models
import django.db.models.deletion
import libs.utils.djangomodelutils
import web.apps.openweathermap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OWMCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OWMWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.CharField(default=None, max_length=128, null=True)),
                ('icon', models.ImageField(default=None, null=True, storage=libs.utils.djangomodelutils.OverwriteStorage(), upload_to=web.apps.openweathermap.models.weather_icon_path)),
            ],
        ),
        migrations.CreateModel(
            name='OWMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('temperature', models.FloatField(default=None, null=True)),
                ('temperature_min', models.FloatField(default=None, null=True)),
                ('temperature_max', models.FloatField(default=None, null=True)),
                ('pressure', models.FloatField(default=None, null=True)),
                ('humidity', models.FloatField(default=None, null=True)),
                ('clouds', models.FloatField(default=None, null=True)),
                ('wind_speed', models.FloatField(default=None, null=True)),
                ('wind_deg', models.FloatField(default=None, null=True)),
                ('snow_3h', models.FloatField(default=None, null=True)),
                ('rain_3h', models.FloatField(default=None, null=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data2city', related_query_name='data2city', to='openweathermap.OWMCities')),
                ('weather', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data2weather', related_query_name='data2weather', to='openweathermap.OWMWeather')),
            ],
        ),
    ]
