# Generated by Django 2.2.23 on 2021-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTaskReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=2048)),
                ('start_date', models.DateField(default=None, null=True)),
                ('start_time', models.TimeField(default=None, null=True)),
                ('duration', models.IntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inProcess', 'inProcess'), ('completed', 'completed'), ('archived', 'archived'), ('expired', 'expired'), ('suspense', 'suspense')], default='pending', max_length=16)),
                ('reminders', models.ManyToManyField(to='todoes.TodoTaskReminder')),
            ],
        ),
    ]
