from .environment import TUVERMIND_REDIS_HOST, TUVERMIND_REDIS_PORT


CELERY_BROKER_URL = f"redis://{TUVERMIND_REDIS_HOST}:{TUVERMIND_REDIS_PORT}"
CELERY_RESULT_BACKEND = f"redis://{TUVERMIND_REDIS_HOST}:{TUVERMIND_REDIS_PORT}"
CELERY_TASK_RESULT_EXPIRES = 600
CELERY_ACCEPT_CONTENT = ['application/json', 'application/x-python-serialize']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Etc/UTC'
CELERY_BEAT_SCHEDULE = {}
CELERY_IMPORTS = ('tasks',)

__all__ = [
    "CELERY_ACCEPT_CONTENT", "CELERY_BEAT_SCHEDULE", "CELERY_BROKER_URL",
    "CELERY_ENABLE_UTC", "CELERY_IMPORTS", "CELERY_RESULT_BACKEND",
    "CELERY_RESULT_SERIALIZER", "CELERY_TASK_RESULT_EXPIRES",
    "CELERY_TASK_SERIALIZER", "CELERY_TIMEZONE"
]
