# Generated by Django 2.1.4 on 2018-12-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OWMCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OWMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('temperature', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('clouds', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('snow_3h', models.FloatField()),
                ('rain_3h', models.FloatField()),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data2city', related_query_name='data2city', to='openweathermap.OWMCities')),
            ],
        ),
        migrations.CreateModel(
            name='OWMWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.CharField(default=None, max_length=128, null=True)),
                ('icon', models.CharField(default=None, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='owmdata',
            name='weather',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data2weather', related_query_name='data2weather', to='openweathermap.OWMWeather'),
        ),
    ]
